apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdcb2f-hpc-pvc
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi